In [1]:
import numpy as np

In [8]:
a=np.random.randn(4,4)
a

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [11]:
a[:]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [12]:
a[1:]

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [13]:
a[::]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [15]:
a[:2:] #rows:columns:step

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623]])

In [16]:
a[::2] 

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554]])

In [17]:
a[1::2]  #1st row,stepping 2

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [19]:
a[-2::]  #accept last 2 rows

array([[ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [25]:
a[1:-1] #middle 2 rows

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554]])

In [27]:
a[::2] #1st and last row

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554]])

In [32]:
a[1::2] #2nd and last row

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [34]:
a[-3:] #last 3 rows

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [39]:
a[:1]  #single 1st column

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902]])

In [38]:
a[::]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [40]:
a[:,1:3]

array([[ 1.04737577, -0.66213641],
       [-1.02631445,  1.08128606],
       [-1.0166055 , -1.38724998],
       [-1.35377049, -0.84452578]])

In [42]:
a[:,1:]

array([[ 1.04737577, -0.66213641, -1.33492902],
       [-1.02631445,  1.08128606,  0.59580623],
       [-1.0166055 , -1.38724998, -0.35072554],
       [-1.35377049, -0.84452578, -0.79933836]])

In [44]:
a[2::]

array([[ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [49]:
a[:-2:]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623]])

In [52]:
a[:][1:3]

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554]])

In [51]:
a[:,100:9] #slicing never gives an error it gives empty o/p.

array([], shape=(4, 0), dtype=float64)

In [59]:
a[2:3,1]

array([-1.0166055])

In [55]:
a[::]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [60]:
a[-1][-1]  #last element

-0.7993383609758474

In [70]:
a[-2:][:,:-2] #last  rows and 1st 2 values from each row.

array([[ 0.30048879, -1.0166055 ],
       [-1.30698362, -1.35377049]])

In [72]:
a[:,1:3]  #access middle 2 columns

array([[ 1.04737577, -0.66213641],
       [-1.02631445,  1.08128606],
       [-1.0166055 , -1.38724998],
       [-1.35377049, -0.84452578]])

In [75]:
a[1:3] #middle 2 rows

array([[ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554]])

In [91]:
a[::-1]  #reverse column

array([[-1.30698362, -1.35377049, -0.84452578, -0.79933836],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [-0.18808385,  1.04737577, -0.66213641, -1.33492902]])

In [93]:
a[::]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [101]:
np.fliplr(a) #flip array from right to left

array([[-1.33492902, -0.66213641,  1.04737577, -0.18808385],
       [ 0.59580623,  1.08128606, -1.02631445,  0.52351898],
       [-0.35072554, -1.38724998, -1.0166055 ,  0.30048879],
       [-0.79933836, -0.84452578, -1.35377049, -1.30698362]])

In [102]:
np.flipud(a) #flip array from bottom to up

array([[-1.30698362, -1.35377049, -0.84452578, -0.79933836],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [-0.18808385,  1.04737577, -0.66213641, -1.33492902]])

In [103]:
a[::a.shape[0]-1, ::a.shape[1]-1]  #corner elements

array([[-0.18808385, -1.33492902],
       [-1.30698362, -0.79933836]])

In [105]:
np.diag(a) #diagonal elements

array([-0.18808385, -1.02631445, -1.38724998, -0.79933836])

In [106]:
a[::]

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])

In [108]:
np.transpose(a)

array([[-0.18808385,  0.52351898,  0.30048879, -1.30698362],
       [ 1.04737577, -1.02631445, -1.0166055 , -1.35377049],
       [-0.66213641,  1.08128606, -1.38724998, -0.84452578],
       [-1.33492902,  0.59580623, -0.35072554, -0.79933836]])

In [109]:
np.ravel(a) #converts any dimension array to 1D. this operation is temporary.

array([-0.18808385,  1.04737577, -0.66213641, -1.33492902,  0.52351898,
       -1.02631445,  1.08128606,  0.59580623,  0.30048879, -1.0166055 ,
       -1.38724998, -0.35072554, -1.30698362, -1.35377049, -0.84452578,
       -0.79933836])

In [114]:
np.resize(a,10)  #it converts an array into any dimensions. It converts in 1D.

array([-0.18808385,  1.04737577, -0.66213641, -1.33492902,  0.52351898,
       -1.02631445,  1.08128606,  0.59580623,  0.30048879, -1.0166055 ])

In [113]:
a

array([[-0.18808385,  1.04737577, -0.66213641, -1.33492902],
       [ 0.52351898, -1.02631445,  1.08128606,  0.59580623],
       [ 0.30048879, -1.0166055 , -1.38724998, -0.35072554],
       [-1.30698362, -1.35377049, -0.84452578, -0.79933836]])