# Numpy

* Background data structure is an array(indexing + slicing).
* Mutable in nature.
* dedicatedly deals with numbers.

In [1]:
import numpy as np

In [5]:
np.__version__

'1.21.5'

In [6]:
np.array?

In [7]:
np.array(100)

array(100)

In [11]:
data1 = np.array([1,2,3,4,5])
data1

array([1, 2, 3, 4, 5])

In [13]:
type(data1)

numpy.ndarray

In [14]:
data1.ndim

1

In [15]:
data1.size #check total elements available in data1

5

In [16]:
len(data1)

5

In [17]:
data1.dtype

dtype('int32')

In [18]:
data1.shape

(5,)

In [21]:
b =np.array([[1,2,3,4],[5,6,7,8]])

In [22]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
b.shape

(2, 4)

In [34]:
c = np.array(b,ndmin=3) #change dimension 1D,2D
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [35]:
c.shape    

(1, 2, 4)

In [36]:
np.array([10,20,30])

array([10, 20, 30])

In [37]:
np.array([10,20,30],dtype='float')  #int to float :upcasting

array([10., 20., 30.])

In [38]:
np.array([2.3,4.1,22.5],dtype='int')  #float to int :downcasting

array([ 2,  4, 22])

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((3,2,2),dtype = 'int')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.full(5,fill_value=50)   #creates an array with constant value

array([50, 50, 50, 50, 50])

In [5]:
np.full((3,4),fill_value=99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

# np.arange() :same as that range() function.

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.sum(np.arange(1,10,2)) #sum between 1 to 10 and step 2.

25

In [8]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
np.arange(10,2,-2)

array([10,  8,  6,  4])

In [15]:
np.random.random(8)     #returns random float numbers

array([0.08497717, 0.10820925, 0.52405862, 0.14209   , 0.11313241,
       0.55344246, 0.13419152, 0.15484797])

In [23]:
np.random.random(5)

array([0.55144425, 0.97583904, 0.25683975, 0.50020122, 0.4674068 ])

In [28]:
np.random.random((3,3))

array([[0.04823983, 0.85229835, 0.54830585],
       [0.3554623 , 0.78446602, 0.98811088],
       [0.84746152, 0.59677934, 0.48213659]])

In [29]:
np.random.random((2,3,3))   #2 blocks ,3 rows ,3 columns

array([[[0.94982524, 0.87581984, 0.97474607],
        [0.69953071, 0.65703601, 0.67575479],
        [0.00331911, 0.33124908, 0.0946749 ]],

       [[0.09111287, 0.34361924, 0.31769383],
        [0.67650846, 0.76750077, 0.05085166],
        [0.4748182 , 0.47069888, 0.98993631]]])

In [65]:
np.random.randn(2,3)   # 2 rows ,3 columns

array([[ 1.99187133, -0.65028483, -1.03040168],
       [ 1.82765051,  1.32837154,  1.11409919]])

In [35]:
np.random.randint(5,10)   #will return a single number between two numbers

8

In [40]:
np.random.randint(5,12,size = 5)

array([ 9, 11, 11,  8,  9])

In [44]:
np.empty(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.empty((3,7))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 1.06811354e-306, 7.56587585e-307,
        1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 2.78149851e-307,
        1.06811422e-306],
       [8.45590539e-307, 6.23054972e-307, 9.34609790e-307,
        1.78019354e-306, 1.69119330e-306, 1.24611470e-306,
        2.56765117e-312]])

In [46]:
np.empty(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [49]:
a.shape

(4, 3)

In [50]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [55]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
a.sum()

66

In [62]:
a.sum(axis = 0)   #addition of columns wise

array([18, 22, 26])

In [63]:
a.sum(axis=1) #addition of row wise

array([ 3, 12, 21, 30])

In [66]:
a.mean()

5.5

In [68]:
average = a.sum()/a.size
average

5.5

In [69]:
a.mean(axis=1)   #row wise

array([ 1.,  4.,  7., 10.])

# a.std()

In [72]:
a.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658])

# OPERATIONS OVER NUMPY ARRAY

In [73]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [74]:
a+100

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [76]:
np.add(a,1000)

array([[1000, 1001, 1002],
       [1003, 1004, 1005],
       [1006, 1007, 1008],
       [1009, 1010, 1011]])

In [77]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
a-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [83]:
multiply =np.multiply(a,5)
multiply

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [84]:
np.power(a,2)

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]], dtype=int32)

In [86]:
np.mod(a,5)

array([[0, 1, 2],
       [3, 4, 0],
       [1, 2, 3],
       [4, 0, 1]], dtype=int32)

In [95]:
p =np.array([[1,2,3,4],[7,8,9,6]])
p

array([[1, 2, 3, 4],
       [7, 8, 9, 6]])

In [93]:
q=np.array([[5,6,7,8],[1,4,7,8]])
q

array([[5, 6, 7, 8],
       [1, 4, 7, 8]])

In [96]:
p+q

array([[ 6,  8, 10, 12],
       [ 8, 12, 16, 14]])

In [97]:
p-q

array([[-4, -4, -4, -4],
       [ 6,  4,  2, -2]])

In [98]:
p*q

array([[ 5, 12, 21, 32],
       [ 7, 32, 63, 48]])

In [99]:
p/q

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [7.        , 2.        , 1.28571429, 0.75      ]])